### PR TITLE
Bugfix/jstricker/table data source not checking visibility

### PR DESCRIPTION
**Pull request by jatraiz**
@KingOfBrian @arrouse here's changes we made to fix a crash for the app we're currently working on. We've been pointing at this branch for the last month and haven't seen any further issues with the collection list.

### CODE REVIEW

**Comment by jatraiz** [comment]
@KingOfBrian @arrouse mind looking at this?

**Comment by KingOfBrian** [comment]
Few notes:
1) Ignoring deviance from RZCodingStandards because it doesn't look like this project obides.  +1 for sticking with the existing style!
2) Are you sure the BOOL is required?   My understanding of NSFRC is that all of it's delegate signaling will occur during one runloop iteration.   So for `beginUpdates` to be called with a window, and other messages to be called without a window would be super rare, and probably only possible by being malicious (IE: mutating the view hierarchy in a `RZCollectionListDataSourceDelegate` method).   Given that this is a weird, timing bug, I'm guessing the BOOL is there to be cautious, but I don't think it's guarding from much.
3)This change forces a substantial change in implementation, since you will always need to reload the view when it will appear.   It seems like it should be documented, even though it's just achieving parity with the (undocumented)behavior of the collection view data source.

**Comment by arrouse** [comment]
@jatraiz would be good to get this merged.  TO @KingOfBrian point.
1) another +1 for that
2) I agree with this question, what was the case (if you remember) that you needed this.  If it is just extra safety I think that is fine.
3) I think with the reloadData (in the `collectionListDidChangeContent`) for the else case will save us from any change in implementation.  You can't animate a tableView when it doesn't have a window so in that case it will just reload the entire list which is probably what you will want..

So I guess if you have any more info about 2 above that would be helpful, Then I think we should merge this.

**Comment by arrouse** [comment]
Also @jatraiz we should change this to merge to develop.

**Comment by jatraiz** [comment]
@KingOfBrian @arrouse 
1) yay +2!
2) there wasn't a specific reason for it, it was just a safety check given that within the class itself it would not call begin under certain conditions I just wanted that condition to apply in case end was called as well 

I'll close this and reopen as a merge request into dev

**Pull request closed without merging**
