### PR TITLE
Adding missing imports

### PR DESCRIPTION
**Pull request by arrouse**
@Raizlabs/maintainers-ios @mgorbach Super simple, just adding some missing imports to some collecitonList files.

### CODE REVIEW

**Comment by ZevEisenberg** [comment]
@Raizlabs/maintainers-ios anyone mind me merging this? The lack of UIKit imports is pretty annoying in a post-pch world.

**Comment by ZevEisenberg** [comment]
@arrouse you could also import `#import <UIKit/UITableView.h>` in the files where you only need those categories.

**Comment by arrouse** [comment]
@ZevEisenberg that is true, but still not great that we rely on anything in UIKit.  We should probably use NSIndexPath creation methods that don't require UIKit.

**Comment by ZevEisenberg** [comment]
@arrouse for code clarity, I'd rather stick with the UIKit categories. What if the underlying implementation of row/item/section change? (Not that they are likely to…)

**Comment by arrouse** [comment]
@ZevEisenberg Well Collectionlist shouldn't be tied to UIKit in anyway except for in the Datasource's.  All of the list classes are usable outside of a UI environment.

**Comment by ZevEisenberg** [comment]
@arrouse right, so I'm about to update this PR with more tightly scoped imports. I also removed some redundant Foundation imports in classes that already import things that import Foundation.

**Comment by ZevEisenberg** [comment]
I also deleted the pch, so that it will be more clear in future that each file must import its own dependencies.

**Pull request merged**
